### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by NeliusNDL** [Onno-Dirkzwager/4-Channel-Relay-Controller#1]
@Onno-Dirkzwager , this link "https://iotappstory.com/community/apps/home-automation/529/4-channel-relay-controller" does not work.

Also I don't know how to contact you, I want to upgrade my IAS account and I don't see any way how to do this ?
Mmm....Best way is the find a issue on your GitHub and see if you get my ping ;-)

**Comment by Onno-Dirkzwager** [comment]
Received! Very busy, will contact you tomorrow

**Comment by Onno-Dirkzwager** [comment]
@NeliusNDL totally slipt my mind at the time. Good to know that we have talked since on other channels.... Reinstated the published apps section last weekend. And only when updating this app did I find this issue again.

https://iotappstory.com/community/publishedapps
